apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: crossplane-package-cache
  namespace: crossplane-system
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 1Gi
